"use strict";
const $=id=>document.getElementById(id);
const num=value=>value==null?"—":new Intl.NumberFormat("pt-BR",{maximumFractionDigits:2}).format(value);
const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const date=value=>value?new Date(value+"T12:00:00").toLocaleDateString("pt-BR"):"—";
const state={summary:null,cities:[],lines:[],loading:false};
const titles={visao:["Visão geral","Uma nova perspectiva<br>sobre o seu trajeto.","Dados que ajudam a entender o transporte entre Maringá e Sarandi."],cidades:["Cidades","O começo de cada conexão.","Organize as cidades que fazem parte da rede de transporte."],linhas:["Linhas de ônibus","Mais organização, em cada linha.","Cadastre linhas e consulte a cidade à qual cada uma pertence."],dados:["Qualidade dos dados","Informação em que você pode confiar.","Conheça a fonte, os critérios e as limitações dos indicadores."]};
function navigate(){const view=location.hash.slice(1)||"visao";const key=titles[view]?view:"visao";document.querySelectorAll(".view").forEach(el=>el.hidden=el.id!==key);document.querySelectorAll("nav a").forEach(el=>{el.classList.toggle("active",el.dataset.view===key);if(el.dataset.view===key)el.setAttribute("aria-current","page");else el.removeAttribute("aria-current");});$("breadcrumb").textContent=titles[key][0];$("page-title").innerHTML=titles[key][1];$("page-description").textContent=titles[key][2];}
async function api(path,options={}){const response=await fetch(path,{...options,signal:AbortSignal.timeout(12000),headers:{"Content-Type":"application/json",...options.headers}});const data=await response.json();if(!response.ok){let message=data.detail;if(Array.isArray(message))message=message.map(e=>e.msg).join("; ");throw new Error(message||"Não foi possível concluir a operação.");}return data;}
function tableEmpty(id,col,text){$(id).innerHTML=`<tr><td colspan="${col}" class="empty">${escapeHtml(text)}</td></tr>`;}
function renderLines(){const query=$("line-search").value.toLocaleLowerCase("pt-BR");const lines=state.lines.filter(l=>`${l.codigo} ${l.nome} ${l.cidade}`.toLocaleLowerCase("pt-BR").includes(query));$("line-table").innerHTML=lines.map(l=>`<tr><td><span class="line-code">${escapeHtml(l.codigo)}</span></td><td>${escapeHtml(l.nome)}</td><td>${escapeHtml(l.cidade)}</td></tr>`).join("");if(!lines.length)tableEmpty("line-table",3,query?"Nenhuma linha encontrada para essa busca.":"Nenhuma linha cadastrada. Comece pelo formulário ao lado.");}
async function loadCities(){const cities=await api("/cidades?limite=500");state.cities=cities;$("city-table").innerHTML=cities.map(c=>`<tr><td class="muted">#${c.id_cidade}</td><td>${escapeHtml(c.nome)}</td></tr>`).join("");if(!cities.length)tableEmpty("city-table",2,"Nenhuma cidade cadastrada. Cadastre a primeira cidade.");const selected=$("line-city").value;$("line-city").innerHTML='<option value="">Selecione uma cidade</option>'+cities.map(c=>`<option value="${c.id_cidade}">${escapeHtml(c.nome)}</option>`).join("");$("line-city").value=selected;}
async function loadLines(){state.lines=await api("/linhas?limite=500");renderLines();}
async function loadSummary(){const s=await api("/ia/resumo");state.summary=s;$("count").textContent=num(s.observacoes_validas);$("mean").textContent=num(s.atraso_medio_min);$("median").textContent=num(s.atraso_mediano_min);$("maximum").textContent=num(s.maior_atraso_min);$("period").textContent=`${date(s.periodo_inicio)} — ${date(s.periodo_fim)}`;$("download").disabled=false;}
async function loadTrend(){const {resultados:rows}=await api("/ia/agrupamentos/data");if(!rows.length){$("trend-chart").innerHTML='<p class="empty">Nenhuma observação disponível.</p>';return;}const width=600,height=190,pad=32,max=Math.max(1,...rows.map(r=>r.atraso_medio_min))*1.15;const x=i=>pad+i*(width-2*pad)/Math.max(1,rows.length-1),y=v=>height-pad-v/max*(height-2*pad);const points=rows.map((r,i)=>`${x(i)},${y(r.atraso_medio_min)}`).join(" ");const grid=[0,1,2,3].map(i=>{const value=max*i/3;return `<line x1="${pad}" y1="${y(value)}" x2="${width-pad}" y2="${y(value)}" stroke="#edf1e8" stroke-dasharray="3 4"/><text x="4" y="${y(value)+3}">${num(Math.round(value))}</text>`;}).join("");$("trend-chart").innerHTML=`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Evolução do atraso médio por dia. Detalhes de cada ponto disponíveis no gráfico."><defs><linearGradient id="fade" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#bed9aa" stop-opacity=".45"/><stop offset="1" stop-color="#bed9aa" stop-opacity="0"/></linearGradient></defs>${grid}<polygon points="${x(0)},${height-pad} ${points} ${x(rows.length-1)},${height-pad}" fill="url(#fade)"/><polyline points="${points}" stroke="#608c64" stroke-width="2.5" fill="none" stroke-linejoin="round"/>${rows.map((r,i)=>`<circle cx="${x(i)}" cy="${y(r.atraso_medio_min)}" r="4" fill="#608c64" tabindex="0"><title>${escapeHtml(date(r.data_registro))}: ${num(r.atraso_medio_min)} min · ${r.observacoes} observações</title></circle>`).join("")}${rows.filter((_,i)=>i%Math.max(1,Math.ceil(rows.length/6))===0||i===rows.length-1).map(r=>`<text x="${x(rows.indexOf(r))}" y="${height-7}" text-anchor="middle">${escapeHtml(date(r.data_registro).slice(0,5))}</text>`).join("")}</svg>`;}
let dimensionRequest=0;
async function loadBars(){const version=++dimensionRequest;const dimension=$("dimension").value;const {resultados:rows}=await api("/ia/agrupamentos/"+dimension);if(version!==dimensionRequest)return;const key={transito:"condicao_transito",cidade:"cidade",periodo:"periodo",clima:"clima"}[dimension];const max=Math.max(1,...rows.map(r=>r.atraso_medio_min));$("bars").innerHTML=rows.length?rows.map(r=>`<div class="bar-item"><div class="bar-label"><span>${escapeHtml(r[key])}<small>${r.observacoes} obs.</small></span><strong>${num(r.atraso_medio_min)} min</strong></div><div class="bar-track"><div class="bar-fill" style="width:${r.atraso_medio_min/max*100}%"></div></div></div>`).join(""):'<p class="empty">Nenhuma observação disponível.</p>';}
async function loadAnalysisLines(){const {resultados:rows}=await api("/ia/agrupamentos/linha");rows.sort((a,b)=>b.atraso_medio_min-a.atraso_medio_min);$("analysis-lines").innerHTML=rows.map(r=>`<tr><td><span class="line-code">${escapeHtml(r.codigo_linha)}</span>${escapeHtml(r.nome_linha)}</td><td class="muted">${escapeHtml(r.cidade)}</td><td>${num(r.observacoes)}</td><td><span class="delay">${num(r.atraso_medio_min)} min</span></td><td class="muted">${num(r.maior_atraso_min)} min</td></tr>`).join("");if(!rows.length)tableEmpty("analysis-lines",5,"Nenhuma observação disponível.");$("analysis-count").textContent=`${rows.length} pares cidade/linha · ordenados por atraso médio`;
}
async function loadQuality(){const q=await api("/ia/qualidade");$("quality-details").innerHTML=`<dl>${[["Registros lidos",q.registros_lidos],["Registros válidos",q.registros_validos],["Registros inválidos",q.registros_excluidos],["Duplicatas adicionais",q.duplicatas_exatas_adicionais]].map(([label,value])=>`<div><dt>${label}</dt><dd>${num(value)}</dd></div>`).join("")}</dl><div class="fingerprint"><strong>Fonte:</strong> ${escapeHtml(q.arquivo)}<br><strong>SHA-256:</strong> ${escapeHtml(q.sha256)}<br>Linhas inválidas e duplicatas interrompem os indicadores até que a fonte seja revisada.</div>`;}
async function loadAll(){if(state.loading)return;state.loading=true;$("refresh").disabled=true;$("download").disabled=true;state.summary=null;for(const id of ["count","mean","median","maximum"])$(id).textContent="—";const errors=[];const jobs=[[async()=>{const h=await api("/health");$("connection").textContent=h.banco==="postgresql"?"PostgreSQL conectado":"Banco local conectado";$("connection").className="connection online";},()=>{$("connection").textContent="Banco indisponível";$("connection").className="connection offline";}],[loadSummary,()=>{$("period").textContent="Indicadores indisponíveis";}],[loadTrend,()=>{$("trend-chart").innerHTML='<p class="empty">Não foi possível carregar a série temporal.</p>';}],[loadBars,()=>{$("bars").innerHTML='<p class="empty">Não foi possível carregar a comparação.</p>';}],[loadAnalysisLines,()=>tableEmpty("analysis-lines",5,"Indicadores indisponíveis.")],[loadCities,()=>{state.cities=[];tableEmpty("city-table",2,"Não foi possível consultar as cidades.");$("line-city").innerHTML='<option value="">Cidades indisponíveis</option>';}],[loadLines,()=>{state.lines=[];tableEmpty("line-table",3,"Não foi possível consultar as linhas.");}],[loadQuality,()=>{$("quality-details").innerHTML='<p class="empty">Auditoria indisponível.</p>';}]];await Promise.all(jobs.map(async([job,failure])=>{try{await job();}catch(error){failure();errors.push(error.message);}}));$("notice").hidden=!errors.length;$("notice").textContent=errors.length?"Algumas informações estão indisponíveis. "+[...new Set(errors)].join(" "):"";$("refresh").disabled=false;state.loading=false;}
function bindForm(id,path,body,after){const form=$(id);form.addEventListener("submit",async event=>{event.preventDefault();const button=form.querySelector("button");const message=form.querySelector(".form-message");button.disabled=true;message.className="form-message";message.textContent="Salvando…";try{await api(path,{method:"POST",body:JSON.stringify(body())});form.reset();message.textContent="Cadastro realizado com sucesso.";try{await after();}catch(error){message.textContent="Cadastro salvo, mas a lista não pôde ser atualizada. Use Atualizar dados.";}}catch(error){message.classList.add("error");message.textContent=error.message;}finally{button.disabled=false;}});}
bindForm("city-form","/cidades",()=>({nome:$("city-name").value.trim()}),loadCities);
bindForm("line-form","/linhas",()=>({id_cidade:Number($("line-city").value),codigo:$("line-code").value.trim(),nome:$("line-name").value.trim()}),loadLines);
$("line-search").addEventListener("input",renderLines);
$("refresh").addEventListener("click",loadAll);
$("dimension").addEventListener("change",()=>{loadBars().catch(error=>{$("bars").innerHTML=`<p class="empty">${escapeHtml(error.message)}</p>`;});});
$("download").disabled=true;$("download").addEventListener("click",()=>{if(!state.summary)return;const url=URL.createObjectURL(new Blob([JSON.stringify(state.summary,null,2)],{type:"application/json"}));const link=document.createElement("a");link.href=url;link.download="transurban-resumo.json";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
window.addEventListener("hashchange",navigate);navigate();loadAll();
