-- =========================================================
-- TRANSURBAN
-- Sistema de apoio ao transporte coletivo
-- Maringá e Sarandi
--
-- Schema inicial do banco de dados
-- PostgreSQL
-- =========================================================

-- ---------------------------------------------------------
-- TABELA: cidade
-- Armazena as cidades atendidas pelo sistema.
-- ---------------------------------------------------------

CREATE TABLE cidade (
    id_cidade INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE
);


-- ---------------------------------------------------------
-- TABELA: linha_onibus
-- Armazena as linhas de transporte coletivo.
-- ---------------------------------------------------------

CREATE TABLE linha_onibus (
    id_linha INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL UNIQUE,
    nome VARCHAR(120) NOT NULL
);


-- ---------------------------------------------------------
-- TABELA: trecho
-- Representa um trecho viário entre duas cidades.
-- ---------------------------------------------------------

CREATE TABLE trecho (
    id_trecho INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_cidade_origem INTEGER NOT NULL,
    id_cidade_destino INTEGER NOT NULL,

    nome VARCHAR(150) NOT NULL,
    distancia_km NUMERIC(6,2) NOT NULL,

    CONSTRAINT fk_trecho_cidade_origem
        FOREIGN KEY (id_cidade_origem)
        REFERENCES cidade (id_cidade),

    CONSTRAINT fk_trecho_cidade_destino
        FOREIGN KEY (id_cidade_destino)
        REFERENCES cidade (id_cidade),

    CONSTRAINT ck_trecho_distancia
        CHECK (distancia_km > 0),

    CONSTRAINT ck_trecho_cidades_diferentes
        CHECK (id_cidade_origem <> id_cidade_destino)
);


-- ---------------------------------------------------------
-- TABELA: linha_trecho
-- Relaciona linhas de ônibus com trechos.
-- Uma linha pode passar por vários trechos.
-- Um trecho pode ser utilizado por várias linhas.
-- ---------------------------------------------------------

CREATE TABLE linha_trecho (
    id_linha INTEGER NOT NULL,
    id_trecho INTEGER NOT NULL,
    ordem INTEGER NOT NULL,

    PRIMARY KEY (id_linha, id_trecho),

    CONSTRAINT fk_linha_trecho_linha
        FOREIGN KEY (id_linha)
        REFERENCES linha_onibus (id_linha),

    CONSTRAINT fk_linha_trecho_trecho
        FOREIGN KEY (id_trecho)
        REFERENCES trecho (id_trecho),

    CONSTRAINT ck_linha_trecho_ordem
        CHECK (ordem > 0),

    CONSTRAINT uq_linha_trecho_ordem
        UNIQUE (id_linha, ordem)
);


-- ---------------------------------------------------------
-- TABELA: faixa_exclusiva
-- Armazena faixas exclusivas ou preferenciais.
-- ---------------------------------------------------------

CREATE TABLE faixa_exclusiva (
    id_faixa INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_trecho INTEGER NOT NULL,

    tipo VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,

    CONSTRAINT fk_faixa_trecho
        FOREIGN KEY (id_trecho)
        REFERENCES trecho (id_trecho),

    CONSTRAINT ck_faixa_tipo
        CHECK (tipo IN ('EXCLUSIVA', 'PREFERENCIAL')),

    CONSTRAINT ck_faixa_status
        CHECK (status IN ('ATIVA', 'INATIVA', 'PLANEJADA'))
);


-- ---------------------------------------------------------
-- TABELA: registro_atraso
-- Registra atrasos observados nas linhas de ônibus.
-- ---------------------------------------------------------

CREATE TABLE registro_atraso (
    id_atraso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_linha INTEGER NOT NULL,
    id_trecho INTEGER NOT NULL,

    data_registro DATE NOT NULL,
    minutos_atraso INTEGER NOT NULL,

    observacao VARCHAR(255),

    CONSTRAINT fk_atraso_linha
        FOREIGN KEY (id_linha)
        REFERENCES linha_onibus (id_linha),

    CONSTRAINT fk_atraso_trecho
        FOREIGN KEY (id_trecho)
        REFERENCES trecho (id_trecho),

    CONSTRAINT ck_atraso_minutos
        CHECK (minutos_atraso >= 0)
);
