-- =========================================================
-- TRANSURBAN
-- Sistema de apoio ao transporte coletivo
--
-- Banco de dados PostgreSQL
-- Compatível exatamente com o CSV da equipe de IA
-- =========================================================


-- ---------------------------------------------------------
-- TABELA: transporte
--
-- Os nomes das colunas abaixo são EXATAMENTE iguais
-- aos nomes presentes no arquivo CSV.
-- ---------------------------------------------------------

CREATE TABLE transporte (

    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    "Cidade" VARCHAR(100) NOT NULL,

    "Código da Linha" VARCHAR(20) NOT NULL,

    "Nome da Linha" VARCHAR(120) NOT NULL,

    "Regiões Atendidas" TEXT NOT NULL,

    "Horários de Referência" TEXT NOT NULL,

    "Informações sobre Atrasos" TEXT NOT NULL

);


-- ---------------------------------------------------------
-- ÍNDICE
--
-- Facilita a busca das linhas por cidade e código.
-- ---------------------------------------------------------

CREATE INDEX idx_transporte_cidade
ON transporte ("Cidade");


CREATE INDEX idx_transporte_codigo_linha
ON transporte ("Código da Linha");


-- ---------------------------------------------------------
-- RESTRIÇÃO
--
-- Impede que a mesma linha seja cadastrada duas vezes
-- na mesma cidade.
-- ---------------------------------------------------------

ALTER TABLE transporte
ADD CONSTRAINT uq_cidade_codigo_linha
UNIQUE ("Cidade", "Código da Linha");
