-- SOMENTE EM BANCO DE TESTES NOVO. Falha sem alterar se as tabelas já existirem.
-- No Supabase existente, execute 01_auditar_supabase.sql primeiro.
BEGIN;
CREATE TABLE public.cidade (
    id_cidade INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE
);
CREATE TABLE public.linha_onibus (
    id_linha INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cidade INTEGER NOT NULL REFERENCES public.cidade(id_cidade),
    codigo VARCHAR(20) NOT NULL,
    nome VARCHAR(100) NOT NULL,
    CONSTRAINT uq_linha_cidade_codigo UNIQUE (id_cidade, codigo)
);
CREATE INDEX ix_linha_onibus_id_cidade ON public.linha_onibus(id_cidade);
ALTER TABLE public.cidade ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.linha_onibus ENABLE ROW LEVEL SECURITY;
-- Nenhuma política pública é criada. A conexão PostgreSQL do backend precisa
-- de papel autorizado para SELECT/INSERT e uso das sequências.
COMMIT;
