-- Migração opcional, NÃO EXECUTADA nesta entrega.
-- Apenas cidade e linha_onibus; preserva registros, chaves e relacionamentos.
-- Use somente após confirmar no script 01 as tabelas public do modelo acadêmico.
-- Execute fora do horário de escrita: mantém bloqueio exclusivo durante a transação.
BEGIN;
LOCK TABLE public.cidade, public.linha_onibus IN ACCESS EXCLUSIVE MODE;
DO $$
DECLARE
    item RECORD;
    identidade TEXT;
    padrao TEXT;
    sequencia TEXT;
    maximo BIGINT;
    ultimo BIGINT;
BEGIN
    FOR item IN SELECT * FROM (VALUES ('cidade', 'id_cidade'), ('linha_onibus', 'id_linha')) AS x(tabela, coluna)
    LOOP
        SELECT is_identity, column_default INTO identidade, padrao
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = item.tabela AND column_name = item.coluna;
        IF NOT FOUND THEN RAISE EXCEPTION 'Coluna não encontrada: %.%', item.tabela, item.coluna; END IF;
        IF identidade = 'NO' AND padrao IS NULL THEN
            EXECUTE format('ALTER TABLE public.%I ALTER COLUMN %I ADD GENERATED BY DEFAULT AS IDENTITY', item.tabela, item.coluna);
        END IF;
        sequencia := pg_get_serial_sequence(format('public.%I', item.tabela), item.coluna);
        IF sequencia IS NULL THEN
            RAISE EXCEPTION 'DEFAULT não reconhecido em %.%; revise manualmente', item.tabela, item.coluna;
        END IF;
        EXECUTE format('SELECT COALESCE(MAX(%I), 0) FROM public.%I', item.coluna, item.tabela) INTO maximo;
        EXECUTE format('SELECT last_value FROM %s', sequencia::regclass) INTO ultimo;
        -- Avança sem diminuir a sequência; lacunas em IDs são normais.
        PERFORM setval(sequencia::regclass, GREATEST(maximo, ultimo, 1), true);
    END LOOP;
END $$;
COMMIT;
